//! On-disk physics layout schema v2 (no per-sample capture timestamp).

use rkyv::{Archive, Deserialize, Serialize};

use super::{CarDamageRecord, ContactPointRecord, Vector3fRecord, WheelsRecord};

#[derive(Archive, Clone, Serialize, Deserialize, Debug)]
#[archive_attr(derive(Debug))]
pub struct PhysicsRecordDiskV2 {
    pub packet_id: i32,

    // Driver inputs
    pub gas: f32,
    pub brake: f32,
    pub clutch: f32,
    pub steer_angle: f32,
    pub gear: i32,
    pub rpm: i32,
    pub autoshifter_on: bool,
    pub ignition_on: bool,
    pub starter_engine_on: bool,
    pub is_engine_running: bool,

    // Car dynamics & motion
    pub speed_kmh: f32,
    pub velocity: Vector3fRecord,
    pub local_velocity: Vector3fRecord,
    pub local_angular_vel: Vector3fRecord,
    pub g_force: Vector3fRecord,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub final_ff: f32,

    // Wheels & tyres
    pub wheel_slip: WheelsRecord,
    pub wheel_load: WheelsRecord,
    pub wheel_pressure: WheelsRecord,
    pub wheel_angular_speed: WheelsRecord,
    pub tyre_wear: WheelsRecord,
    pub tyre_dirty_level: WheelsRecord,
    pub tyre_core_temp: WheelsRecord,
    pub camber_rad: WheelsRecord,
    pub suspension_travel: WheelsRecord,
    pub brake_temp: WheelsRecord,
    pub brake_pressure: WheelsRecord,
    pub suspension_damage: WheelsRecord,
    pub slip_ratio: WheelsRecord,
    pub slip_angle: WheelsRecord,
    pub pad_life: WheelsRecord,
    pub disc_life: WheelsRecord,
    pub front_brake_compound: i32,
    pub rear_brake_compound: i32,
    pub tyre_temp_i: WheelsRecord,
    pub tyre_temp_m: WheelsRecord,
    pub tyre_temp_o: WheelsRecord,
    pub tyre_temp_extra: WheelsRecord,

    // Tyre contact patches
    pub tyre_contact_point: ContactPointRecord,
    pub tyre_contact_normal: ContactPointRecord,
    pub tyre_contact_heading: ContactPointRecord,

    // Car status
    pub fuel: f32,
    pub tc: f32,
    pub abs: f32,
    pub pit_limiter_on: bool,
    pub turbo_boost: f32,
    pub air_temp: f32,
    pub road_temp: f32,
    pub water_temp: f32,
    pub car_damage: CarDamageRecord,
    pub is_ai_controlled: bool,
    pub brake_bias: f32,
    pub tc_in_action: bool,
    pub abs_in_action: bool,

    // Additional physics data
    pub drs: i32,
    pub cg_height: f32,
    pub number_of_tyres_out: i32,
    pub kers_charge: f32,
    pub kers_input: f32,
    pub ride_height_front: f32,
    pub ride_height_rear: f32,
    pub ballast: f32,
    pub air_density: f32,
    pub performance_meter: f32,
    pub engine_brake: i32,
    pub ers_recovery_level: i32,
    pub ers_power_level: i32,
    pub ers_heat_charging: i32,
    pub ers_is_charging: i32,
    pub kers_current_kj: f32,
    pub drs_available: i32,
    pub drs_enabled: i32,
    pub p2p_activation: i32,
    pub p2p_status: i32,
    pub current_max_rpm: i32,
    pub mz: WheelsRecord,
    pub fz: WheelsRecord,
    pub my: WheelsRecord,

    // Vibration
    pub kerb_vibration: f32,
    pub slip_vibration: f32,
    pub g_vibration: f32,
    pub abs_vibration: f32,

}

impl From<PhysicsRecordDiskV2> for super::PhysicsRecord {
    fn from(v: PhysicsRecordDiskV2) -> Self {
        Self {
            packet_id: v.packet_id,
            gas: v.gas,
            brake: v.brake,
            clutch: v.clutch,
            steer_angle: v.steer_angle,
            gear: v.gear,
            rpm: v.rpm,
            autoshifter_on: v.autoshifter_on,
            ignition_on: v.ignition_on,
            starter_engine_on: v.starter_engine_on,
            is_engine_running: v.is_engine_running,
            speed_kmh: v.speed_kmh,
            velocity: v.velocity,
            local_velocity: v.local_velocity,
            local_angular_vel: v.local_angular_vel,
            g_force: v.g_force,
            heading: v.heading,
            pitch: v.pitch,
            roll: v.roll,
            final_ff: v.final_ff,
            wheel_slip: v.wheel_slip,
            wheel_load: v.wheel_load,
            wheel_pressure: v.wheel_pressure,
            wheel_angular_speed: v.wheel_angular_speed,
            tyre_wear: v.tyre_wear,
            tyre_dirty_level: v.tyre_dirty_level,
            tyre_core_temp: v.tyre_core_temp,
            camber_rad: v.camber_rad,
            suspension_travel: v.suspension_travel,
            brake_temp: v.brake_temp,
            brake_pressure: v.brake_pressure,
            suspension_damage: v.suspension_damage,
            slip_ratio: v.slip_ratio,
            slip_angle: v.slip_angle,
            pad_life: v.pad_life,
            disc_life: v.disc_life,
            front_brake_compound: v.front_brake_compound,
            rear_brake_compound: v.rear_brake_compound,
            tyre_temp_i: v.tyre_temp_i,
            tyre_temp_m: v.tyre_temp_m,
            tyre_temp_o: v.tyre_temp_o,
            tyre_temp_extra: v.tyre_temp_extra,
            tyre_contact_point: v.tyre_contact_point,
            tyre_contact_normal: v.tyre_contact_normal,
            tyre_contact_heading: v.tyre_contact_heading,
            fuel: v.fuel,
            tc: v.tc,
            abs: v.abs,
            pit_limiter_on: v.pit_limiter_on,
            turbo_boost: v.turbo_boost,
            air_temp: v.air_temp,
            road_temp: v.road_temp,
            water_temp: v.water_temp,
            car_damage: v.car_damage,
            is_ai_controlled: v.is_ai_controlled,
            brake_bias: v.brake_bias,
            tc_in_action: v.tc_in_action,
            abs_in_action: v.abs_in_action,
            drs: v.drs,
            cg_height: v.cg_height,
            number_of_tyres_out: v.number_of_tyres_out,
            kers_charge: v.kers_charge,
            kers_input: v.kers_input,
            ride_height_front: v.ride_height_front,
            ride_height_rear: v.ride_height_rear,
            ballast: v.ballast,
            air_density: v.air_density,
            performance_meter: v.performance_meter,
            engine_brake: v.engine_brake,
            ers_recovery_level: v.ers_recovery_level,
            ers_power_level: v.ers_power_level,
            ers_heat_charging: v.ers_heat_charging,
            ers_is_charging: v.ers_is_charging,
            kers_current_kj: v.kers_current_kj,
            drs_available: v.drs_available,
            drs_enabled: v.drs_enabled,
            p2p_activation: v.p2p_activation,
            p2p_status: v.p2p_status,
            current_max_rpm: v.current_max_rpm,
            mz: v.mz,
            fz: v.fz,
            my: v.my,
            kerb_vibration: v.kerb_vibration,
            slip_vibration: v.slip_vibration,
            g_vibration: v.g_vibration,
            abs_vibration: v.abs_vibration,
            capture_time_sec: 0.0,
        }
    }
}
