//! rkyv layout **schema v1** (initial recorder; header `binary_file_version == 1`).
//!
//! V2 adds `PhysicsRecord::tyre_temp_extra`, `GraphicsRecord::{replay_time_multiplier, surface_grip, i_split}`,
//! and `StaticsRecord::track_spline_length`. See `format_meta` and `export::rkyv_format`.

use rkyv::{Archive, Deserialize, Serialize};

use super::{
    CarDamageRecord, ContactPointRecord, GraphicsRecord, PhysicsRecord, StaticsRecord, Vector3fRecord,
    WheelsRecord,
};

/// Physics snapshot schema v1 (no `tyre_temp_extra`).
#[derive(Archive, Clone, Serialize, Deserialize, Debug)]
#[archive_attr(derive(Debug))]
pub struct PhysicsRecordV1 {
    pub packet_id: i32,
    pub gas: f32,
    pub brake: f32,
    pub clutch: f32,
    pub steer_angle: f32,
    pub gear: i32,
    pub rpm: i32,
    pub autoshifter_on: bool,
    pub ignition_on: bool,
    pub starter_engine_on: bool,
    pub is_engine_running: bool,
    pub speed_kmh: f32,
    pub velocity: Vector3fRecord,
    pub local_velocity: Vector3fRecord,
    pub local_angular_vel: Vector3fRecord,
    pub g_force: Vector3fRecord,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub final_ff: f32,
    pub wheel_slip: WheelsRecord,
    pub wheel_load: WheelsRecord,
    pub wheel_pressure: WheelsRecord,
    pub wheel_angular_speed: WheelsRecord,
    pub tyre_wear: WheelsRecord,
    pub tyre_dirty_level: WheelsRecord,
    pub tyre_core_temp: WheelsRecord,
    pub camber_rad: WheelsRecord,
    pub suspension_travel: WheelsRecord,
    pub brake_temp: WheelsRecord,
    pub brake_pressure: WheelsRecord,
    pub suspension_damage: WheelsRecord,
    pub slip_ratio: WheelsRecord,
    pub slip_angle: WheelsRecord,
    pub pad_life: WheelsRecord,
    pub disc_life: WheelsRecord,
    pub front_brake_compound: i32,
    pub rear_brake_compound: i32,
    pub tyre_temp_i: WheelsRecord,
    pub tyre_temp_m: WheelsRecord,
    pub tyre_temp_o: WheelsRecord,
    pub tyre_contact_point: ContactPointRecord,
    pub tyre_contact_normal: ContactPointRecord,
    pub tyre_contact_heading: ContactPointRecord,
    pub fuel: f32,
    pub tc: f32,
    pub abs: f32,
    pub pit_limiter_on: bool,
    pub turbo_boost: f32,
    pub air_temp: f32,
    pub road_temp: f32,
    pub water_temp: f32,
    pub car_damage: CarDamageRecord,
    pub is_ai_controlled: bool,
    pub brake_bias: f32,
    pub tc_in_action: bool,
    pub abs_in_action: bool,
    pub drs: i32,
    pub cg_height: f32,
    pub number_of_tyres_out: i32,
    pub kers_charge: f32,
    pub kers_input: f32,
    pub ride_height_front: f32,
    pub ride_height_rear: f32,
    pub ballast: f32,
    pub air_density: f32,
    pub performance_meter: f32,
    pub engine_brake: i32,
    pub ers_recovery_level: i32,
    pub ers_power_level: i32,
    pub ers_heat_charging: i32,
    pub ers_is_charging: i32,
    pub kers_current_kj: f32,
    pub drs_available: i32,
    pub drs_enabled: i32,
    pub p2p_activation: i32,
    pub p2p_status: i32,
    pub current_max_rpm: i32,
    pub mz: WheelsRecord,
    pub fz: WheelsRecord,
    pub my: WheelsRecord,
    pub kerb_vibration: f32,
    pub slip_vibration: f32,
    pub g_vibration: f32,
    pub abs_vibration: f32,
}

/// Graphics snapshot schema v1 (no trailing ACC graphic slots).
#[derive(Archive, Clone, Serialize, Deserialize, Debug)]
#[archive_attr(derive(Debug))]
#[derive(serde::Serialize, serde::Deserialize)]
pub struct GraphicsRecordV1 {
    pub packet_id: i32,
    pub status: i32,
    pub session_type: i32,
    pub session_index: i32,
    pub current_time_str: String,
    pub last_time_str: String,
    pub best_time_str: String,
    pub last_sector_time_str: String,
    pub completed_lap: i32,
    pub position: i32,
    pub current_time: i32,
    pub last_time: i32,
    pub best_time: i32,
    pub last_sector_time: i32,
    pub number_of_laps: i32,
    pub delta_lap_time_str: String,
    pub estimated_lap_time_str: String,
    pub delta_lap_time: i32,
    pub estimated_lap_time: i32,
    pub is_delta_positive: bool,
    pub is_valid_lap: bool,
    pub fuel_estimated_laps: f32,
    pub distance_traveled: f32,
    pub normalized_car_position: f32,
    pub session_time_left: f32,
    pub current_sector_index: i32,
    pub is_in_pit: bool,
    pub is_in_pit_lane: bool,
    pub ideal_line_on: bool,
    pub mandatory_pit_done: bool,
    pub missing_mandatory_pits: i32,
    pub penalty_time: f32,
    pub penalty: i32,
    pub flag: i32,
    pub player_car_id: i32,
    pub active_cars: i32,
    pub car_coordinates_x: f32,
    pub car_coordinates_y: f32,
    pub car_coordinates_z: f32,
    pub wind_speed: f32,
    pub wind_direction: f32,
    pub rain_intensity: i32,
    pub rain_intensity_in_10min: i32,
    pub rain_intensity_in_30min: i32,
    pub track_grip_status: i32,
    pub track_status: String,
    pub clock: f32,
    pub tc_level: i32,
    pub tc_cut_level: i32,
    pub engine_map: i32,
    pub abs_level: i32,
    pub wiper_stage: i32,
    pub driver_stint_total_time_left: i32,
    pub driver_stint_time_left: i32,
    pub rain_tyres: bool,
    pub rain_light: bool,
    pub flashing_light: bool,
    pub light_stage: i32,
    pub direction_light_left: bool,
    pub direction_light_right: bool,
    pub tyre_compound: String,
    pub is_setup_menu_visible: bool,
    pub main_display_index: i32,
    pub secondary_display_index: i32,
    pub fuel_per_lap: f32,
    pub used_fuel: f32,
    pub exhaust_temp: f32,
    pub gap_ahead: i32,
    pub gap_behind: i32,
    pub global_yellow: bool,
    pub global_yellow_s1: bool,
    pub global_yellow_s2: bool,
    pub global_yellow_s3: bool,
    pub global_white: bool,
    pub global_green: bool,
    pub global_chequered: bool,
    pub global_red: bool,
    pub mfd_tyre_set: i32,
    pub mfd_fuel_to_add: f32,
    pub mfd_tyre_pressure_fl: f32,
    pub mfd_tyre_pressure_fr: f32,
    pub mfd_tyre_pressure_rl: f32,
    pub mfd_tyre_pressure_rr: f32,
    pub current_tyre_set: i32,
    pub strategy_tyre_set: i32,
}

fn zero_wheels() -> WheelsRecord {
    WheelsRecord {
        front_left: 0.0,
        front_right: 0.0,
        rear_left: 0.0,
        rear_right: 0.0,
    }
}

impl From<PhysicsRecordV1> for PhysicsRecord {
    fn from(v: PhysicsRecordV1) -> Self {
        Self {
            packet_id: v.packet_id,
            gas: v.gas,
            brake: v.brake,
            clutch: v.clutch,
            steer_angle: v.steer_angle,
            gear: v.gear,
            rpm: v.rpm,
            autoshifter_on: v.autoshifter_on,
            ignition_on: v.ignition_on,
            starter_engine_on: v.starter_engine_on,
            is_engine_running: v.is_engine_running,
            speed_kmh: v.speed_kmh,
            velocity: v.velocity,
            local_velocity: v.local_velocity,
            local_angular_vel: v.local_angular_vel,
            g_force: v.g_force,
            heading: v.heading,
            pitch: v.pitch,
            roll: v.roll,
            final_ff: v.final_ff,
            wheel_slip: v.wheel_slip,
            wheel_load: v.wheel_load,
            wheel_pressure: v.wheel_pressure,
            wheel_angular_speed: v.wheel_angular_speed,
            tyre_wear: v.tyre_wear,
            tyre_dirty_level: v.tyre_dirty_level,
            tyre_core_temp: v.tyre_core_temp,
            camber_rad: v.camber_rad,
            suspension_travel: v.suspension_travel,
            brake_temp: v.brake_temp,
            brake_pressure: v.brake_pressure,
            suspension_damage: v.suspension_damage,
            slip_ratio: v.slip_ratio,
            slip_angle: v.slip_angle,
            pad_life: v.pad_life,
            disc_life: v.disc_life,
            front_brake_compound: v.front_brake_compound,
            rear_brake_compound: v.rear_brake_compound,
            tyre_temp_i: v.tyre_temp_i,
            tyre_temp_m: v.tyre_temp_m,
            tyre_temp_o: v.tyre_temp_o,
            tyre_temp_extra: zero_wheels(),
            tyre_contact_point: v.tyre_contact_point,
            tyre_contact_normal: v.tyre_contact_normal,
            tyre_contact_heading: v.tyre_contact_heading,
            fuel: v.fuel,
            tc: v.tc,
            abs: v.abs,
            pit_limiter_on: v.pit_limiter_on,
            turbo_boost: v.turbo_boost,
            air_temp: v.air_temp,
            road_temp: v.road_temp,
            water_temp: v.water_temp,
            car_damage: v.car_damage,
            is_ai_controlled: v.is_ai_controlled,
            brake_bias: v.brake_bias,
            tc_in_action: v.tc_in_action,
            abs_in_action: v.abs_in_action,
            drs: v.drs,
            cg_height: v.cg_height,
            number_of_tyres_out: v.number_of_tyres_out,
            kers_charge: v.kers_charge,
            kers_input: v.kers_input,
            ride_height_front: v.ride_height_front,
            ride_height_rear: v.ride_height_rear,
            ballast: v.ballast,
            air_density: v.air_density,
            performance_meter: v.performance_meter,
            engine_brake: v.engine_brake,
            ers_recovery_level: v.ers_recovery_level,
            ers_power_level: v.ers_power_level,
            ers_heat_charging: v.ers_heat_charging,
            ers_is_charging: v.ers_is_charging,
            kers_current_kj: v.kers_current_kj,
            drs_available: v.drs_available,
            drs_enabled: v.drs_enabled,
            p2p_activation: v.p2p_activation,
            p2p_status: v.p2p_status,
            current_max_rpm: v.current_max_rpm,
            mz: v.mz,
            fz: v.fz,
            my: v.my,
            kerb_vibration: v.kerb_vibration,
            slip_vibration: v.slip_vibration,
            g_vibration: v.g_vibration,
            abs_vibration: v.abs_vibration,
            capture_time_sec: 0.0,
        }
    }
}

impl From<GraphicsRecordV1> for GraphicsRecord {
    fn from(v: GraphicsRecordV1) -> Self {
        Self {
            packet_id: v.packet_id,
            status: v.status,
            session_type: v.session_type,
            session_index: v.session_index,
            current_time_str: v.current_time_str,
            last_time_str: v.last_time_str,
            best_time_str: v.best_time_str,
            last_sector_time_str: v.last_sector_time_str,
            completed_lap: v.completed_lap,
            position: v.position,
            current_time: v.current_time,
            last_time: v.last_time,
            best_time: v.best_time,
            last_sector_time: v.last_sector_time,
            number_of_laps: v.number_of_laps,
            delta_lap_time_str: v.delta_lap_time_str,
            estimated_lap_time_str: v.estimated_lap_time_str,
            delta_lap_time: v.delta_lap_time,
            estimated_lap_time: v.estimated_lap_time,
            is_delta_positive: v.is_delta_positive,
            is_valid_lap: v.is_valid_lap,
            fuel_estimated_laps: v.fuel_estimated_laps,
            distance_traveled: v.distance_traveled,
            normalized_car_position: v.normalized_car_position,
            session_time_left: v.session_time_left,
            current_sector_index: v.current_sector_index,
            is_in_pit: v.is_in_pit,
            is_in_pit_lane: v.is_in_pit_lane,
            ideal_line_on: v.ideal_line_on,
            mandatory_pit_done: v.mandatory_pit_done,
            missing_mandatory_pits: v.missing_mandatory_pits,
            penalty_time: v.penalty_time,
            penalty: v.penalty,
            flag: v.flag,
            player_car_id: v.player_car_id,
            active_cars: v.active_cars,
            car_coordinates_x: v.car_coordinates_x,
            car_coordinates_y: v.car_coordinates_y,
            car_coordinates_z: v.car_coordinates_z,
            wind_speed: v.wind_speed,
            wind_direction: v.wind_direction,
            rain_intensity: v.rain_intensity,
            rain_intensity_in_10min: v.rain_intensity_in_10min,
            rain_intensity_in_30min: v.rain_intensity_in_30min,
            track_grip_status: v.track_grip_status,
            track_status: v.track_status,
            clock: v.clock,
            tc_level: v.tc_level,
            tc_cut_level: v.tc_cut_level,
            engine_map: v.engine_map,
            abs_level: v.abs_level,
            wiper_stage: v.wiper_stage,
            driver_stint_total_time_left: v.driver_stint_total_time_left,
            driver_stint_time_left: v.driver_stint_time_left,
            rain_tyres: v.rain_tyres,
            rain_light: v.rain_light,
            flashing_light: v.flashing_light,
            light_stage: v.light_stage,
            direction_light_left: v.direction_light_left,
            direction_light_right: v.direction_light_right,
            tyre_compound: v.tyre_compound,
            is_setup_menu_visible: v.is_setup_menu_visible,
            main_display_index: v.main_display_index,
            secondary_display_index: v.secondary_display_index,
            fuel_per_lap: v.fuel_per_lap,
            used_fuel: v.used_fuel,
            exhaust_temp: v.exhaust_temp,
            gap_ahead: v.gap_ahead,
            gap_behind: v.gap_behind,
            global_yellow: v.global_yellow,
            global_yellow_s1: v.global_yellow_s1,
            global_yellow_s2: v.global_yellow_s2,
            global_yellow_s3: v.global_yellow_s3,
            global_white: v.global_white,
            global_green: v.global_green,
            global_chequered: v.global_chequered,
            global_red: v.global_red,
            mfd_tyre_set: v.mfd_tyre_set,
            mfd_fuel_to_add: v.mfd_fuel_to_add,
            mfd_tyre_pressure_fl: v.mfd_tyre_pressure_fl,
            mfd_tyre_pressure_fr: v.mfd_tyre_pressure_fr,
            mfd_tyre_pressure_rl: v.mfd_tyre_pressure_rl,
            mfd_tyre_pressure_rr: v.mfd_tyre_pressure_rr,
            current_tyre_set: v.current_tyre_set,
            strategy_tyre_set: v.strategy_tyre_set,
            replay_time_multiplier: 1.0,
            surface_grip: 0.0,
            i_split: 0,
        }
    }
}

/// Statics schema v1 (no `track_spline_length`).
#[derive(Clone, serde::Serialize, serde::Deserialize, Debug)]
pub struct StaticsRecordV1 {
    pub sm_version: String,
    pub ac_version: String,
    pub number_of_sessions: i32,
    pub num_cars: i32,
    pub track: String,
    pub sector_count: i32,
    pub player_name: String,
    pub player_surname: String,
    pub player_nick: String,
    pub car_model: String,
    pub max_rpm: i32,
    pub max_fuel: f32,
    pub penalty_enabled: bool,
    pub aid_fuel_rate: f32,
    pub aid_tyre_rate: f32,
    pub aid_mechanical_damage: f32,
    pub aid_stability: f32,
    pub aid_auto_clutch: bool,
    pub pit_window_start: i32,
    pub pit_window_end: i32,
    pub is_online: bool,
    pub dry_tyres_name: String,
    pub wet_tyres_name: String,
}

impl From<StaticsRecordV1> for StaticsRecord {
    fn from(v: StaticsRecordV1) -> Self {
        Self {
            sm_version: v.sm_version,
            ac_version: v.ac_version,
            number_of_sessions: v.number_of_sessions,
            num_cars: v.num_cars,
            track: v.track,
            sector_count: v.sector_count,
            player_name: v.player_name,
            player_surname: v.player_surname,
            player_nick: v.player_nick,
            car_model: v.car_model,
            max_rpm: v.max_rpm,
            max_fuel: v.max_fuel,
            penalty_enabled: v.penalty_enabled,
            aid_fuel_rate: v.aid_fuel_rate,
            aid_tyre_rate: v.aid_tyre_rate,
            aid_mechanical_damage: v.aid_mechanical_damage,
            aid_stability: v.aid_stability,
            aid_auto_clutch: v.aid_auto_clutch,
            pit_window_start: v.pit_window_start,
            pit_window_end: v.pit_window_end,
            is_online: v.is_online,
            dry_tyres_name: v.dry_tyres_name,
            wet_tyres_name: v.wet_tyres_name,
            track_spline_length: 0.0,
        }
    }
}

impl From<StaticsRecord> for StaticsRecordV1 {
    fn from(v: StaticsRecord) -> Self {
        Self {
            sm_version: v.sm_version,
            ac_version: v.ac_version,
            number_of_sessions: v.number_of_sessions,
            num_cars: v.num_cars,
            track: v.track,
            sector_count: v.sector_count,
            player_name: v.player_name,
            player_surname: v.player_surname,
            player_nick: v.player_nick,
            car_model: v.car_model,
            max_rpm: v.max_rpm,
            max_fuel: v.max_fuel,
            penalty_enabled: v.penalty_enabled,
            aid_fuel_rate: v.aid_fuel_rate,
            aid_tyre_rate: v.aid_tyre_rate,
            aid_mechanical_damage: v.aid_mechanical_damage,
            aid_stability: v.aid_stability,
            aid_auto_clutch: v.aid_auto_clutch,
            pit_window_start: v.pit_window_start,
            pit_window_end: v.pit_window_end,
            is_online: v.is_online,
            dry_tyres_name: v.dry_tyres_name,
            wet_tyres_name: v.wet_tyres_name,
        }
    }
}
